---
- name: install zsh packages
  apt: pkg={{ item }} state=present
  tags: [packages]
  with_items:
    - zsh
    - zsh-doc
    - curl

- name: Install oh my zsh"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ username }}/.oh-my-zsh
    depth: 1

- name: Install zsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
        

- name: change user shell to zsh 
  user:
    name: "{{ username }}"
    shell: /bin/zsh 

- name: Copy zshrc file"
  copy:
    src: ./configs/.zshrc
    dest: /home/{{ username  }}/.zshrc
