---
- name: Update apt cache
  apt: update-cache=yes cache_valid_time=86400

- name: Update all packages
  apt: upgrade=dist

- name: install basic packages
  apt: pkg={{ item }} state=latest
  tags: [packages]
  with_items:
    - curl
    - vim
    - libxslt1-dev 
    - libxml2-dev
    - zip
    - libssl-dev
    - unzip
    - apg
    - mercurial
    - git

- name: Ensure that ansible_cache_dir directory exists
  file: path={{ ansible_cache_dir }} state=directory
